export const INCREASE_COUNT = "INCREASE_COUNT";
export const INCREASE_COUNT_SUCCESS = "INCREASE_COUNT_SUCCESS";

export const DECREASE_COUNT = "DECREASE_COUNT";
export const DECREASE_COUNT_SUCCESS = "DECREASE_COUNT_SUCCESS";

export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_REQUEST_SUCCESS = "GET_DATA_REQUEST_SUCCESS";
export const GET_DATA_REQUEST_ERROR = "GET_DATA_REQUEST_ERROR";

export const GET_ANIMAL_REQUEST = "GET_ANIMAL_REQUEST";
export const GET_ANIMAL_REQUEST_SUCCESS = "GET_ANIMAL_REQUEST_SUCCESS";
export const GET_ANIMAL_REQUEST_ERROR = "GET_ANIMAL_REQUEST_ERROR";
